### PR TITLE
I136 fix margin between save button and navbar in contactdetails page

### LINKED ISSUE #136: Fix margin between Save button and navbar in ContactDetails page
image

The save button needs some bottom margin to separate it from the navbar

### PR DESCRIPTION
**Pull request by ok7097269**
## Change Summary
**[fix margin between save button and navbar in contactdetails page]**

### Change Form
**Fill this up (NA if not available). If a certain criteria is not met, can you please give a reason.**

- [x] The pull request title has an issue number
- [ ] The change works by "Smoke testing" or quick testing
- [ ] The change has tests
- [ ] The change has documentation

## Other Information
**[Is there anything in particular in the review that I should be aware of?]**

# Related Issue

- Resolve #136

### CODE REVIEW

File: src/components/Contact/contactform.tsx [hunk 1]
```diff
@@ -200,7 +200,6 @@ const ContactForm = ({
               </Button>
             )}
           </div>
```
Comment (skyheat) [inline src/components/Contact/contactform.tsx:202]: Looks like you have a formatting issue here. Make sure to run prettier :)

**Review by skyheat — CHANGES_REQUESTED** [review]
Looks good! Just a formatting issue.

**Review by NicholasChoong — COMMENTED** [review]
Why is there a submodule of the repo itself?

**Review by skyheat — APPROVED** [review]
